### ISSUE TITLE
Does TagCloud support click event and custom color?

### ISSUE THREAD

**Issue by kybetter** [mcc108/TagCloud#7]
I have these two demand right now, and I browse TagCloud source code but can't find relation setting.

Can you add these two attributes? I think it is a most people's demand.

^_^

**Comment by whelmin** [comment]
You can use event delegation to add custom events, add classes to the container, and complete custom styles. For these demand, we have perfected the documentation. You can read more details in the [README](https://github.com/mcc108/TagCloud/blob/master/README.md)

**Comment by kybetter** [comment]
Thank you, I got it.
In fact, I want every child has different color, and I wrote style bellow:
```css
.diy .tagcloud--item:nth-child(0) {
    color: #67C23A;
}
.diy .tagcloud--item:nth-child(1) {
    color: #67323b;
}
// more...
```
